decentraland/ui

- src/components/Navbar/Navbar.css
- src/components/Navbar/Navbar.tsx
> feat: mobile support for navbar

- package-lock.json
- package.json
Modals are broken in semantic-ui-react@0.81.x
Updated semantic-ui-react (tested on Builder via npm link)
[logo]:  https://media2.giphy.com/media/OK27wINdQS5YQ/giphy.gif "Logo Title Text 2"
> chore: updated semantic ui

- src/components/LanguageDropdown/LanguageDropdown.stories.tsx
- src/components/LanguageDropdown/LanguageDropdown.tsx
- test/coverage/__snapshots__/coverage.test.ts.snap
fix: language dropdown default locales
> fix: language dropdown default locales

- src/components/Navbar/Navbar.css
> fix: mobile navbar

- src/components/Footer/Footer.tsx
- test/coverage/__snapshots__/coverage.test.ts.snap
> fix: update copyright

- src/components/Field/Field.stories.tsx
- src/components/Field/Field.tsx
Hides the field action on error/loading and type=address, firing a console.warn for this last one
> fix: hide field action when necessary

- package-lock.json
- src/components/Atlas/Atlas.tsx
> fix: prevent Atlas state update when unmounted

- src/components/Field/Field.tsx
- src/components/Filter/Filter.stories.tsx
- src/components/SelectField/Select.stories.tsx
- src/components/SelectField/SelectField.css
- src/components/SelectField/SelectField.tsx
- src/index.ts
> feat: select field

- package-lock.json
- package.json
- src/components/SelectField/SelectField.css
- src/components/SelectField/SelectField.stories.tsx
- src/components/TagField/TagField.css
- src/components/TagField/TagField.stories.tsx
- src/components/TagField/TagField.tsx
- src/index.ts
> feat: tag field

- src/components/Atlas/Atlas.tsx
Remove `getDerivedStateFromProps` and `newTiles` and `forceUpdate`
> chore: remove newTiles, getDerivedStateFromProps and forceUpdate

- src/components/Footer/Footer.css
**From**
**To**
Closes https://github.com/decentraland/builder/issues/658
> fix: update footer for medium resolutions

- package-lock.json
- package.json
- src/components/Mana/Mana.css
- src/components/Mana/Mana.stories.tsx
- src/components/Mana/Mana.tsx
- src/components/UserMenu/UserMenu.stories.tsx
- src/components/UserMenu/UserMenu.tsx
- src/index.ts
BREAKING CHANGE: no more use of "mana" prop, instead use of "manaBalances"
> feat: use mana balances per network

- src/components/LoginModal/LoginModal.css
- src/components/LoginModal/LoginModal.stories.tsx
- src/components/LoginModal/LoginModal.tsx
Adds the `message` prop to LoginModal
> feat: add a customizable message to the LoginModal

- src/components/TextAreaField/TextAreaField.css
- src/components/TextAreaField/TextAreaField.stories.tsx
This PR fixes the styles in the text areas when they're embedded into forms.
> fix: Styles for text areas in forms

- package-lock.json
- package.json
- src/components/Loader/Loader.css
- src/components/Loader/Loader.stories.tsx
- src/components/LoginModal/LoginModal.css
- src/components/LoginModal/LoginModal.stories.tsx
- src/components/LoginModal/LoginModal.tsx
Dependency: 
- https://github.com/decentraland/common-schemas/pull/53
> feat: Add wallet link to login options and wallet loader

- src/components/Box/Box.css
- src/components/Box/Box.stories.tsx
- src/components/Box/Box.tsx
- src/components/ToggleBox/ToggleBox.css
- src/components/ToggleBox/ToggleBox.stories.tsx
- src/components/ToggleBox/ToggleBox.tsx
Added ToogleBox component that use Box Component
> feat: added Box and ToggleBox components

- package-lock.json
- package.json
- src/components/WearablePreview/WearablePreview.stories.tsx
- src/components/WearablePreview/WearablePreview.tsx
Added support for `urls` and `base64s` props, also used shared types and helper for sending/handling preview messages.
> feat: added support for wearables from urls and base64

- src/components/WearablePreview/WearablePreview.stories.tsx
- src/components/WearablePreview/WearablePreview.tsx
Added props that were missing in the URL
> fix(WearablePreview): add missing params to the url

- src/components/Navbar/Navbar.tsx
- src/components/UserMenu/UserMenu.tsx
Related: https://github.com/decentraland/marketplace/issues/618 https://github.com/decentraland/marketplace/pull/620
> feat: two decimal places for mana values

- package-lock.json
- package.json
- src/components/WearablePreview/WearablePreview.tsx
- tsconfig.json
Added support for an `onUpdate` callback to the `WearablePreview`. This callback combined with the already existing `onLoad` can be combined to show loading states on the parent UI while the preview is processing updates.
> feat(WearablePreview): onUpdate callback

- package-lock.json
- package.json
- src/components/WearablePreview/WearablePreview.tsx
This PR adds support to the `WearablePreview` component for the wheel related options of the `wearable-preview` app.
> feat: added support for wheel options

- src/components/LoginModal/LoginModal.css
- src/components/LoginModal/LoginModal.stories.tsx
- src/components/LoginModal/LoginModal.tsx
> feat: Update Coinbase Wallet label

- src/components/SliderField/SliderField.css
Related to [this](https://github.com/decentraland/events/issues/241) issue
> fix: remove from SliderField width and height fixed

- src/components/WearablePreview/WearablePreview.tsx
> fix(WearablePreview): background param

- package-lock.json
- package.json
- src/components/WearablePreview/WearablePreview.controller.ts
This PR adds support for the emote events
> feat: add support for emote events

- src/components/WearablePreview/EmoteControls.css
- src/components/WearablePreview/EmoteControls.tsx
- src/components/WearablePreview/WearablePreview.css
- src/components/WearablePreview/WearablePreview.stories.tsx
Closes #185
https://user-images.githubusercontent.com/8763687/182611278-35ffa3c9-adf8-458f-977c-e723aa1bebcf.mov
> feat: Add EmoteControls component

- package-lock.json
- package.json
- src/components/WearablePreview/WearablePreview.stories.tsx
- src/components/WearablePreview/WearablePreview.tsx
This PR adds support for orthographic projection and custom camera position + stories to show how they work
> feat: added support for orthographic projection and camera position

- src/components/WearablePreview/EmoteControls.tsx
The `play` handler has an async action, it's always trying to get the `length`. There are times where an `END` action is triggered really close to the play one and the play is slower than it due to the async call.
It shouldn't ask for the length it was already obtained before.
> fix: fixes race condition due to play having an async action

- src/components/WearablePreview/WearablePreview.stories.tsx
- src/components/WearablePreview/WearablePreview.tsx
This PR adds the `peerUrl`, `nftServerUrl` and `disableFadeEffect` props to the `WearablePreview` component.
> feat: added peerUrl, nftServerUrl and disableFadeEffect props

- src/components/Toast/Toast.stories.css
- src/components/Toast/Toast.stories.tsx
- src/components/Toast/Toast.tsx
This PR adds the property className to the toast, allowing set styles from the invoker component.
> feat: Add property className to the toast

- src/components/Field/Field.css
- src/components/Field/Field.stories.tsx
- src/components/Field/Field.tsx
- src/components/RangeField/RangeField.css
- src/components/RangeField/RangeField.stories.tsx
- src/components/RangeField/RangeField.tsx
- Add new range component
- Add kind to input field (default simple) so that we can have inputs with borders
> feat: add range field component

- src/components/RangeField/index.ts
- src/index.ts
Add new component `RangeField` to index.ts so it can be imported
> fix: add range field to index

- src/components/Box/Box.css
- src/components/Box/Box.stories.tsx
- src/components/Box/Box.tsx
- src/components/Box/index.ts
- src/components/RangeField/RangeField.tsx
- src/index.ts
Add collapsible feature to box component
https://user-images.githubusercontent.com/11800206/208768133-24083fee-d716-4103-9a72-7fc1ba73687c.mov
> feat: add collapsible prop to box

- src/components/Box/Box.css
- src/components/Box/Box.tsx
use semantic ui icon instead of importing from assets as its causing build error on marketplace ui
> fix: use semantic ui icon for box

- src/components/BuyManaWithFiatModal/BuyManaWithFiatModal.stories.tsx
- src/components/BuyManaWithFiatModal/FeedbackModal.css
- src/components/BuyManaWithFiatModal/FeedbackModal.tsx
> feat: Add pending failure buy mana feedback modal designs

- package-lock.json
- package.json
- src/components/Field/Field.css
- src/components/Field/Field.stories.tsx
- src/components/Field/Field.tsx
> feat: field support on datepicker

- src/components/Field/Field.stories.tsx
- src/components/RangeField/RangeField.stories.tsx
- src/components/RangeField/RangeField.tsx
Add the possiblity to send additional props to range field component so there is more flexibility when used
> feat: add additional props to range field

- src/components/Box/Box.css
- src/components/Box/Box.tsx
Add defaultCollapsed and permit the header to be a jsx element
> feat: add new properties to box

- src/components/Checkbox/Checkbox.css
- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Radio/Radio.css
Add checkbox component for toggles as it permits to change with space
> feat: add checkbox component

- src/components/Mana/Mana.css
- src/components/Mana/Mana.stories.tsx
- src/components/Mana/Mana.tsx
Related to the "Buy NFTs with Card" EPIC
https://github.com/decentraland/marketplace/pull/1369
> feat: Add flag to Mana component allowing changing it to primary

- src/components/BarChart/BarChart.tsx
> fix: BarChart: apply decimals to the input values as well

- src/components/BarChart/BarChart.css
- src/components/SliderField/SliderField.css
Change slider styles so that they are consistent across the web
> fix: change slider styles

- src/components/LoginModal/LoginModal.css
- src/components/LoginModal/LoginModal.tsx
- src/components/Modal/Modal.css
> feat: added metamask mobile

- src/components/BarChart/BarChart.css
- src/components/BarChart/BarChart.tsx
- src/components/BarChart/utils.ts
- src/components/RangeField/RangeField.tsx
> fix: bar chart labels

- package-lock.json
- package.json
- src/components/Atlas/Atlas.stories.tsx
Bump version of tile-map library to have zoomControls
> feat: bump tile-map lib version with zoom controls

- src/components/BarChart/BarChart.tsx
- src/components/BarChart/BarChart.types.ts
Send in onChange event for BarChart filter the source where the event is coming from:
- Input: the change event was triggered due to a change in the input
- chart: the change event was triggered due to the user clicking on the chart
- slider: the change event was triggered due to a change in the slider
This will allow us to track how the user interacts with the component
> feat: add bar chart filter source onChange

- src/components/BarChart/BarChart.tsx
- src/components/BarChart/BarChart.types.ts
- src/components/Loader/Loader.tsx
- src/components/RangeField/RangeField.tsx
Add aria labels and ids so that loader and bar chart are accessible
Closes #310 #311
> fix: accessiblity for loader and barchart

- src/components/WearablePreview/WearablePreview.stories.tsx
This PR upgrades the storybook format for the component WearablePreview allowing override of the global layout property
> feat: Upgrade WearablePreview storybook format

- src/components/Mana/Mana.stories.tsx
- src/components/Mana/Mana.tsx
Related to https://github.com/decentraland/marketplace/issues/699
> feat : Add tooltips to MANA component

- src/components/Navbar/Navbar.css
- src/components/Navbar/Navbar.stories.tsx
- src/components/Navbar/Navbar.tsx
This PR adds default submenus to the dapps sections.
> feat: Add dapps submenu

- src/components/Navbar/Navbar.css
- src/components/Navbar/Navbar.tsx
This PR updates the navbar submenu spacing and mobile view.
Desktop
Mobile
> feat: Update navbar submenus

- src/components/AvatarFace/AvatarFace.tsx
- src/components/Blockie/Blockie.tsx
- src/components/Profile/Profile.stories.tsx
- src/components/Profile/Profile.tsx
- src/types/as.ts
Related to https://github.com/decentraland/marketplace/issues/1561
> feat: Profile allows the prop as to render its content with a different behavior

- src/components/Profile/Profile.stories.tsx
- src/components/Profile/Profile.tsx
- src/types/as.ts
Related to https://github.com/decentraland/marketplace/pull/1561
> fix: Avoid a default value for the generic

- src/components/UserMenu/UserMenu.css
- src/components/UserMenu/UserMenu.tsx
This PR updates the user balance styles when the numbers are too high.
> feat: Update user balances

- src/components/Navbar/Navbar.tsx
This PR fixes error when not defined onClickMenuOption
> fix: Error when not defined onClickMenuOption

- src/components/AuthorizationModal/AuthorizationModal.tsx
> fix: close wording

- src/components/AuthorizationModal/AuthorizationModal.css
- src/components/AuthorizationModal/AuthorizationModal.stories.tsx
- src/components/MultiStep/MultiStep.css
Improve error icon in authorization modal component
> fix: authorization error icon

- src/themes/base-theme.css
It can be updated directly on the library
> feat(WC2): Remove w3modal style

- src/components/Field/Field.stories.tsx
- src/components/Field/Field.tsx
This PR changes the message type of the Field component to allow components to be rendered.
> feat: Allow react nodes as messages in Field

- src/components/Field/Field.css
- src/components/Field/Field.stories.tsx
- src/components/Field/Field.tsx
This PR adds the capability to show information and warnings in the message below the inputs.
> feat: Add warning and info messages to Field

- src/components/AuthorizationModal/AuthorizationModal.css
- src/components/AuthorizationModal/AuthorizationModal.stories.tsx
Fix authorization error icon position to be align with text and add more margin for authorization header in mobile so it doesn't collide with the close button
> fix: authorization icon position

- src/themes/base-theme.css
This pull request introduces a reusable rarity color scheme to the base theme, enabling consistent color coding across multiple sites. 
This approach ensures colors consistency.
> feat: add rarity colors to base-theme

- src/components/AvatarFace/AvatarFace.tsx
> feat: Add className prop to AvatarFace component

- package-lock.json
- package.json
> feat: bump schemas

- src/components/AssetCard/AssetCard.stories.tsx
- src/components/AssetCard/AssetCard.tsx
- src/components/AssetImage/AssetImage.css
This PR fixes some issues with wearable images going over the card.
> fix: Image size

- src/components/UserMenu/UserMenu.tsx
This PR adds a temporal prop `newMenu` to render the old user menu and the new user menu
> fix: Add temporal prop to render old user menu and new user menu

- package-lock.json
- package.json
- src/components/WearablePreview/WearablePreview.stories.tsx
- src/components/WearablePreview/WearablePreview.tsx
This PR adds the wearable preview locking and panning parameters.
> feat: Add wearable preview locking

- src/components/UserInformationContainer/UserInformationContainer.css
- src/components/UserInformationContainer/UserInformationContainer.tsx
This reverts commit 4f286aec2c85fb26a1793a35b5fb942fcc76bbb4.
> Revert "fix: change initial state and css variable names"

- src/components/WearablePreview/EmoteControls.css
- src/components/WearablePreview/EmoteControls.tsx
> fix: asset import

- src/components/AssetImage/AssetImage.css
- src/components/AssetImage/AssetImage.tsx
- src/components/CatalogCard/CatalogCard.css
Rename assetimage css class so that it doesn't collide with other dapps
> fix: asset image css

- src/components/WearablePreview/EmoteControls.tsx
Resume playing emote when emote was previously playing
> feat: resume play emote

- src/components/CategoryFilter/CategoryFilter.css
- src/components/CategoryFilter/CategoryFilter.stories.tsx
- src/components/CategoryFilter/CategoryFilter.tsx
- src/components/CategoryFilter/CategoryFilter.types.ts
- src/components/CategoryFilter/CategoryFilterItem/CategoryFilterItem.css
- src/components/CategoryFilter/CategoryFilterItem/CategoryFilterItem.tsx
- src/components/CategoryFilter/CategoryFilterItem/CategoryFilterItem.types.ts
- src/components/CategoryFilter/CategoryFilterItem/index.ts
Closes https://github.com/decentraland/profile/issues/218
Abstract and simplify the Category Filter from the marketplace so it can also be used in the profile dapp.
> feat: Category Filter

- package-lock.json
- package.json
- src/components/Navbar/Navbar.tsx
- src/components/UserInformationContainer/UserInformationContainer.tsx
- src/components/UserMenu/UserMenu.tsx
- src/components/WearablePreview/WearablePreview.stories.tsx
- src/components/WearablePreview/WearablePreview.tsx
- src/config/env/dev.json
- src/config/env/prod.json
- src/config/env/stg.json
- src/config/index.ts
- tsconfig.json
Add env-ui library to handle redirection to correct URL insttead of always going to `.org`
> feat: add ui env to redirect to correct environemtn

- package-lock.json
- src/components/ArrayFilter/ArrayFilter.css
- src/components/ArrayFilter/ArrayFilter.spec.tsx
- src/components/ArrayFilter/ArrayFilter.stories.tsx
- src/components/ArrayFilter/ArrayFilter.tsx
- src/components/ArrayFilter/ArrayFilter.types.ts
- src/components/ArrayFilter/index.ts
- src/index.ts
This PR extracts the ArrayFilter component into the UI repository.
Closes #401
> feat: Add the ArrayFilter component

- README.md
- src/components/UserInformationContainer/UserInformationContainer.css
Storybook Before/After
Governance Before/After
Guest Before/After
> fix: remove top margin from activity-icon

- src/components/AssetStatusFilter/AssetStatusFilter.css
- src/components/AssetStatusFilter/AssetStatusFilter.spec.tsx
- src/components/AssetStatusFilter/AssetStatusFilter.stories.css
- src/components/AssetStatusFilter/AssetStatusFilter.stories.tsx
- src/components/AssetStatusFilter/AssetStatusFilter.tsx
- src/components/AssetStatusFilter/AssetStatusFilter.types.ts
- src/components/AssetStatusFilter/constants.ts
- src/components/AssetStatusFilter/index.ts
- src/index.ts
This PR adds the asset status filter.
Closes #440
> feat: Add asset status filter

- src/components/BackToTopButton/BackToTopButton.css
- src/components/BackToTopButton/BackToTopButton.stories.tsx
- src/components/BackToTopButton/BackToTopButton.tsx
- src/components/BackToTopButton/BackToTopButton.types.ts
- src/components/BackToTopButton/index.ts
- src/index.ts
> feat: Introduce BackToTopButton

- src/components/Card/Card.tsx
- src/components/NFTCard/NFTCard.css
- src/components/NFTCard/NFTCard.stories.tsx
- src/components/NFTCard/NFTCard.tsx
- src/components/NFTCard/NFTCard.types.ts
Add additional card props to NFTCard
> feat: add additional properties to NFT card

- package-lock.json
- package.json
- src/components/UserInformationContainer/UserInformationContainer.stories.tsx
- src/components/UserInformationContainer/UserInformationContainer.tsx
This PR does the following:
- Adds a new method to track menu items clicks
- Generates a tracking id when the menu opens and uses it when calling the new method so the data team can link the actions.
- Executes the new method on each click if it's defined.
> fix: User information tracking

- src/components/UserInformationContainer/UserInformationContainer.stories.tsx
- src/components/UserInformationContainer/UserInformationContainer.tsx
> fix: add hash piece to the avatar name if not claimed

- src/components/Button/Button.css
| before | after |
|-------|------|
| <img width="389" alt="Screenshot 2023-10-30 at 14 11 34" src="https://github.com/decentraland/ui/assets/208789/6ac4e2b4-e705-45ce-9b01-e6a0f3d3d605"> | <img width="378" alt="Screenshot 2023-10-30 at 14 11 45" src="https://github.com/decentraland/ui/assets/208789/c99cc822-368b-459b-9720-abf4f595b8c4"> |
> fix: button state for `.inverted` and `.inverted.primary`

- src/components/NFTCard/NFTCard.stories.tsx
- src/components/Profile/Profile.stories.tsx
- src/config/env/dev.json
- src/config/env/prod.json
- src/config/env/stg.json
Change url for static sites from subdomain to paths
> feat: change domain to path for static sites

- src/config/env/dev.json
- src/config/env/prod.json
- src/config/env/stg.json
This PR changes the links to the new ones.
> fix: Update links

- src/components/UserMenu/UserMenuSignedIn/UserMenuSignedIn.css
- src/components/UserMenu/UserMenuSignedIn/UserMenuSignedIn.tsx
> fix: UserMenu default image

- src/components/Navbar2/Navbar2.tsx
- src/components/Navbar2/Navbar2.types.ts
- src/components/Navbar2/SubMenu/SubMenu.types.ts
- src/components/Navbar2/SubMenuItem/SubMenuItem.tsx
- src/components/Navbar2/SubMenuItem/SubMenuItem.types.ts
- src/components/UserMenu/UserMenu.tsx
- src/components/UserMenu/UserMenuSignedIn/UserMenuSignedIn.css
- src/components/UserMenu/UserMenuSignedIn/UserMenuSignedIn.tsx
- src/components/UserMenu/UserMenuSignedIn/UserMenuSignedIn.types.ts
Changed tracking props from `onClickMenuItem` by `onClickNavbarItem` and `onClickUserMenuItem`
> feat: change navbar2 link behavior and tracking props

- src/components/Navbar/Navbar.tsx
- src/config/env/dev.json
- src/config/env/prod.json
- src/config/env/stg.json
> feat: add names link to the navbar

- src/components/Navbar2/Navbar2.css
- src/components/Navbar2/Navbar2.tsx
This PR: 
- fixes: https://github.com/decentraland/catalyst/issues/1724
> fix: Navbar2 bugs

- package-lock.json
- src/components/v2/Table/Table.stories.tsx
- src/components/v2/Table/TableContainer/TableContainer.css
- src/components/v2/Table/TableContainer/TableContainer.tsx
- src/components/v2/Table/TableContainer/TableContianer.types.tsx
- src/components/v2/Table/TableContainer/index.tsx
- src/components/v2/Table/TableContent/TableContent.css
- src/components/v2/Table/TableContent/TableContent.spec.tsx
- src/components/v2/Table/TableContent/TableContent.tsx
- src/components/v2/Table/TableContent/TableContent.types.tsx
- src/components/v2/Table/TableContent/index.tsx
- src/components/v2/index.ts
Move TableContent and TableContainer from the marketplace to ui to be able to reuse it
> feat: add table v2

- src/components/v2/Table/Table.stories.tsx
- src/components/v2/Table/TableContent/TableContent.spec.tsx
- src/components/v2/Table/TableContent/TableContent.tsx
- src/components/v2/Table/TableContent/TableContent.types.tsx
Add possibility to set custom headers for some attributes in Table (V2) component
> feat: add custom headers for table v2 component

- src/components/AddressField/AddressField.types.ts
- src/components/AddressField/index.ts
- src/index.ts
AddressField `resolveName` function can return a promise
> fix: address field prop types

- src/components/AddressField/AddressField.tsx
> fix: remove use effect

- src/components/AddressField/AddressField.spec.tsx
- src/components/AddressField/AddressField.tsx
- src/components/AddressField/AddressField.types.ts
Call `onChange` callback everytime the user changes the value of the address field, even if its not valid
> fix: AddressField onChange callback

- src/components/Notifications/Notifications.css
- src/components/Notifications/Notifications.tsx
Add animation when there are new notifications
> feat: add notifications animation

- .github/workflows/master.yml
- .github/workflows/pr.yml
- package.json
This PR changes the UI repository to use Node 18 instead of Node 16.
> feat: Use Node 18

- src/components/Tabs/Tabs.tsx
> fix: tabs rendering undefined value as className

- .storybook/theme.tsx
- README.md
- src/components/IconBadge/IconBadge.css
- src/components/Notifications/NotificationsFeed.css
- src/themes/alternative/dark-theme.css
- src/themes/alternative/light-theme.css
> feat: notification light theme

- src/components/CatalogCard/CatalogCard.css
- src/components/CatalogCard/CatalogCard.stories.tsx
- src/components/CatalogCard/CatalogCard.tsx
- src/components/NFTCard/NFTCard.stories.tsx
- src/components/NFTCard/NFTCard.tsx
- src/components/NFTCard/NFTCard.types.ts
- src/components/NFTCard/utils.tsx
- src/components/RarityBadge/RarityBadge.css
- src/components/RarityBadge/RarityBadge.stories.css
- src/components/RarityBadge/RarityBadge.stories.tsx
- src/components/RarityBadge/RarityBadge.tsx
- src/components/RarityBadge/RarityBadge.types.ts
- src/components/RarityBadge/index.ts
- src/index.ts
- src/lib/colors.ts
This PR adds the new rarity badge and changes the cards to have the new badge as well.
> feat: Add new rarity badge

- src/components/RarityBadge/RarityBadge.css
This PR fixes the centering of the `RarityBadge` text.
> fix: RarityBadge flex

- src/components/CatalogCard/CatalogCard.stories.tsx
This PR makes the catalog card capable of being controllable in storybook.
> fix: Make catalog card controllable

- src/components/Blockie/Blockie.css
- src/components/Blockie/Blockie.stories.tsx
- src/components/Blockie/Blockie.tsx
This PR makes it possible to have a rounded Blockie component.
> feat: Allow rounded blockie
