decentraland/ui

codecov.yaml

This PR disabled CodeCov's patch check and bot comment

chore: disabled codecov comment and patch

---

src/components/Atlas/Atlas.tsx

fix: avoid overwriting Atlas state with undefined tiles

---

src/components/SelectField/SelectField.css
src/components/SelectField/SelectField.stories.tsx
src/components/SelectField/SelectField.tsx

feat: added support for error and message props in SelectField

---

src/components/Modal/Modal.stories.tsx

This PR changes the word `wan` to `want`, fixing a typo in the modal's storybook.

Fix small typo in the modal's storybook

---

src/components/Loader/Loader.css
src/components/LoginModal/LoginModal.css

This PR replace the use of `url(...)` for `inline(...)` to prevent compilation fails on some frameworks:

fix: image import on css

---

src/components/Container/Container.css
src/components/Footer/Footer.stories.css
src/components/Footer/Footer.stories.tsx
src/components/Footer/Footer.tsx
src/components/Navbar/Navbar.stories.tsx
src/components/Navbar/Navbar.tsx

Added fullWidth prop for navbar / footer components to match new docs site design:
https://www.figma.com/file/qJabYQmkRIQWMLRbGRCvj9/Documentation?node-id=1454%3A4509

feat: add fullwidth style to match docs design request

---

.gitignore
package-lock.json
package.json
src/components/WearablePreview/WearablePreview.stories.tsx
src/components/WearablePreview/WearablePreview.tsx
src/lib/debounce.ts

This PR adds support to changing props in the `WearablePreview` component without refreshing the iframe. To do this, the URL of the iframe is stored in the component's state when it's mounted, and is never updated again even if the props are changed, this preserves the iframe between renders. In order to communicate the updated properties to the iframe, this is done passing messages using `postMessage`. These messages are debounced 500ms to batch multiple changes together in a single update.
This PR also upgraded to the latest `@dcl/schemas` version and uses the shared preview types.
I also added some properties that were already supported on the `wearable-preview` app but were not wired in the `WearablePreview` component, like `autoRotateSpeed`, `offsetX`, `offsetY`, `offsetZ`, …

feat: send updates via postMessage

---

src/components/AvatarFace/AvatarFace.tsx
src/components/Mana/Mana.stories.tsx
src/components/Mana/Mana.tsx
src/components/Profile/Profile.tsx
src/components/UserMenu/UserMenu.stories.tsx
src/components/UserMenu/UserMenu.tsx
src/components/WearablePreview/WearablePreview.stories.tsx
src/components/WearablePreview/WearablePreview.tsx
src/data/avatar.ts

some browsers are getting the following error when we import directly from `@dcl/schemas`
```
Uncaught SyntaxError: Invalid flags supplied to RegExp constructor 'u'
```
This PR replace all directs imports from `@dcl/schemas` in favor of each specific file to prevent this error and also reduce the bundle size of the library

fix: @dcl/schemas imports

---

src/components/WearablePreview/WearablePreview.tsx

This fixes the current issue in the marketplace with hot reload. Once the hot reload feature is fixed we can remove this flag and make it the default behavior.
I tested this in the marketplace using the release candidate `v3.30.1-rc3`

fix: make hot-reload optional

---

src/components/ToggleBox/ToggleBox.stories.tsx
src/components/ToggleBox/ToggleBox.tsx

This is related to #157 
the value property was added to the ToggleBox and ToggleBox item, eliminating the active property. 
This way we leave to the component the work of selecting the correct item.

feat: add value to ToggleBox component

---

package-lock.json
package.json
src/components/WearablePreview/WearablePreview.tsx

This PR integrates the `ready` message from the wearable-preview iframe (for reference: https://github.com/decentraland/wearable-preview/pull/31). It keeps track of the ready-ness of the iframe with a boolean in state, and the updates that arrive before the iframe is ready are stored in state too (only the last update is kept in state since each update overrides the previous ones). Once the `ready` message arrives, if there was any pending update stored in state it is flushed back to the iframe. This way messages sent while the iframe is loading are not lost.

feat(WearablePreview): integrate ready message

---

package-lock.json
package.json
src/components/WearablePreview/WearablePreview.controller.ts
src/components/WearablePreview/WearablePreview.stories.css
src/components/WearablePreview/WearablePreview.stories.tsx
src/components/WearablePreview/WearablePreview.tsx

This PR adds the integration against the `wearable-preview` [controller RPC](https://github.com/decentraland/wearable-preview#controller-rpc).
I also added support for a `blob` property which is now supported by the `wearable-preview`.
I added 4 stories illustrating how to use the new features like taking screenshots, showing metrics, controlling an emote animation and rendering wearables/emotes from zip files

feat(WearablePreview): controller RPC integration

---

src/components/WearablePreview/WearablePreview.stories.tsx
src/components/WearablePreview/WearablePreview.tsx

This PR adds support for the `WearablePreview` component to use the custom background color feature already supported by the `wearable-preview`

feat(WearablePreview): support custom background color

---

src/components/WearablePreview/WearablePreview.controller.ts

Fix issue where two controller for the same iframe are created at different times, and the nonce is reseted, mixing the promises of the requests and responses.

fix: prevent reseting nonce

---

src/components/WearablePreview/WearablePreview.tsx

Adds the `disableDefaultEmotes` to disable the default Emotes animations.

feat: add disableDefaultEmotes prop to the WearablePreview component

---

package-lock.json
package.json
src/components/WearablePreview/WearablePreview.tsx

This PR bumps `@dcl/schemas` to the latest version. It removes the now deprecated `PreviewEnv` since now the `wearable-preview` uses `@dcl/ui-env`: https://github.com/decentraland/wearable-preview/pull/54

chore: upgrade @dcl/schemas

---

package-lock.json
package.json
src/components/WearablePreview/EmoteControls.tsx
src/components/WearablePreview/WearablePreview.controller.ts

This PR refactorizes the `EmoteControl` component to consume the current frame from the WearablePreview using the event `animation_playing`
depends on: https://github.com/decentraland/common-schemas/pull/143

fix: Emotes animation progress length

---

src/components/Toasts/Toasts.css
src/components/Toasts/Toasts.stories.tsx
src/components/Toasts/Toasts.tsx

This PR adds a center position for toasts.
Top Center:
Bottom Center:

feat: Add center position for toasts

---

src/components/Toast/Toast.css
src/components/Toast/Toast.stories.tsx
src/components/Toast/Toast.tsx
src/modules.d.ts

This PR adds the possiblity to set an icon in the toast component. This is an optional property

feat: add icon to toast

---

src/components/Box/Box.css
src/components/Radio/Radio.css

Add outline on focus to radios and collapsible box chevron

feat: add outline to radio and collapsible box

---

src/components/BarChart/BarChart.stories.tsx
src/components/BarChart/BarChart.tsx
src/components/BarChart/BarChart.types.ts
src/components/BarChart/BarChartTooltip.tsx

We are gonna use the BarChart for units that are not in MANA, so we should support sending a boolean to avoid rendering the MANA icon

feat: Add "isMana" prop to BarChart

---

src/components/BarChart/BarChart.css
src/components/BarChart/BarChart.tsx
src/components/SliderField/SliderField.css
src/components/SliderField/SliderField.stories.tsx
src/components/SliderField/SliderField.tsx

Make slider component accessible following [W3C](https://www.w3.org/WAI/ARIA/apg/patterns/slider-multithumb/examples/slider-multithumb/) recommendations 
- Make values of slider follow the thumb and not be static at the sides of the component
- Move labels to the top of the slider to make it more usable for mobile users
- Add roles and labels

feat: make slider accesible

---

package-lock.json
package.json
src/themes/base-theme.css

Required because DCL's sign in modal has a z-index of 3000 and shows in front of the wallet connect v2 modal.
By overriding wc2 to 3001 it is fixed.

feat(WC2): Override Wallet Connect V2 Modal Styles

---

src/components/Navbar/Navbar.stories.css
src/components/NetworkAlert/NetworkAlert.css
src/components/NetworkAlert/NetworkAlert.stories.tsx
src/components/NetworkAlert/NetworkAlert.tsx
src/components/NetworkAlert/NetworkAlert.types.ts

This PR adds the NetworkAlert component that will be used as the replacement for the modal that shows the `PartiallySupported` network alert.

feat: Add the NetworkAlert component

---

package-lock.json
package.json

Bump tile-map library version so that iti includes new event `onCenterChange`

fix: bump tile map library version

---

src/components/BarChart/BarChart.tsx

When clicking the last bar in the barchart the values in handleChange are being sent as a number without being parse to string causing function `fixedNumber` to fail and the selection never being applied. This pr parses the number to string so `match` function can be called

fix: error selecting upper bound on bar charts

---

package-lock.json
package.json

This PR updates react-tile map to its latest version which removes `react-virtualized`, supporting react 17 and 18.

fix: Update react tile map

---

src/components/Toasts/Toasts.css

Related to https://github.com/decentraland/marketplace/issues/1595

fix: Use the min and necessary width for the centered toasts container

---

src/components/Navbar/Navbar.css
src/components/Navbar/Navbar.tsx

This PR adds a new prop `onClickMenuOption` to pass a custom handler when clicking on the navbar menu or submenus options. It also fixes navbar click priority, letting the user click the navbar option directly.

feat: Add onClickMenuOption prop

---

src/components/Navbar/Navbar.css

This PR fixes the active navbar item that doesn't show bolded.

fix: Navbar active item font weight

---

src/components/Field/Field.css
src/components/Field/Field.stories.tsx
src/components/Field/Field.tsx
src/lib/input.ts

When `maxLength` is set, add the length count and its max length next to its label.

feat: Make field count the text length when maxLength is set

---

src/components/TextAreaField/TextAreaField.css
src/components/TextAreaField/TextAreaField.stories.tsx
src/components/TextAreaField/TextAreaField.tsx

This PR adds the max length count on the top right of the TextArea component when the prop is set.

feat: Add max length count for the TextArea component

---

src/components/TextAreaField/TextAreaField.tsx

This PR adds a missing blank space in the TextAreaField component that sets a space for the message to exist.

fix: Add blankspace to TextAreaField message

---

src/components/Navbar/Navbar.tsx

This PR adds the `worlds` option to the navbar.

feat: Add worlds option to the navbar

---

src/components/SelectField/SelectField.tsx

Needed to render the header of the fields in the create item flow as follows:

feat: Extend select field accepting elements as labels

---

src/components/WearablePreview/EmoteControls.tsx

The wearable preview send an event of "PLAY" everytime a frame changes. This is to ignore those events while sliding the frame as it will cause the emote to resume playing even when at the start of the change it was on pause

feat: ignore playing event when using slider

---

src/components/Radio/Radio.css
src/components/RadioOptions/RadioOptions.css
src/components/RadioOptions/RadioOptions.spec.tsx
src/components/RadioOptions/RadioOptions.stories.css
src/components/RadioOptions/RadioOptions.stories.tsx
src/components/RadioOptions/RadioOptions.tsx
src/components/RadioOptions/RadioOptions.types.ts
src/components/RadioOptions/index.ts

This PR adds the `RadioOptions` component which generates a radio group with radio buttons given a set of options.
It also changes the `Radio` styles for the new ones that are already working in the Marketplace.

feat: Add Radio Options component

---

src/components/SideMenu/SideMenu.css

This PR removes the `overflow` property which was preventing the component from growing and the `padding-bottom` which is not necessary.

fix: Small side menu changes

---

src/components/CategoryFilter/CategoryFilter.css

This PR removes some CSS properties that aren't needed anymore.

fix: Remove some CategoryFilter's styles

---

src/components/UserInformationContainer/UserInformationContainer.tsx

This PR makes the UserInformationContainer wait when clicking any of its options before opening a new window to give time to the tracking methods to work.

fix: Wait some time before executing the tracking methods

---

src/components/Profile/Profile.stories.tsx
src/components/Profile/Profile.tsx

This PR adds the missing hashtag that was removed in a breaking change in the way the profiles are saved.

fix: Add hashtag on profile names

---

src/components/Navbar/MenuItem/MenuItem.css

This PR capitalizes the texts in the mobile menu:

fix: Capitalize mobile menu

---

src/components/Tabs/Tabs.css

Now styles are similar to new navbar.
Closes decentraland/governance#1355

feat: update tabs idle and hover styles

---

src/components/ChainSelector/ChainSelector.css

This PR changes the `ChainSelector` chain classes by scoping them to the component to avoid leaking to other components.

fix: Scope chain icons to modal and button

---

src/components/TextAreaField/TextAreaField.css
src/components/TextAreaField/TextAreaField.stories.tsx
src/components/TextAreaField/TextAreaField.tsx

This PR adds the capability of adding a tooltip to the TextAreaField component.

feat: Add tooltip to text area

---

src/components/IconBadge/IconBadge.css
src/components/IconBadge/IconBadge.tsx

This PR makes the IconBadge component show a pointer only if it has the onClick method prop set.

fix: Show Icon Badge pointer if clickable

---

src/components/UserMenu/UserMenu.css
src/components/UserMenu/UserMenu.stories.css
src/components/UserMenu/UserMenu.stories.tsx
src/components/UserMenu/UserMenu.tsx
src/components/UserMenu/UserMenu.types.ts

This PR does the following:
- Adds a disconnecting loader when the user is disconnecting their wallet.
- Makes the jump in button visible only when the user is logged in.

feat: Add disconnecting loader

---

src/components/SelectField/SelectField.css
src/components/SelectField/SelectField.tsx

This PR changes the `SelectField` CSS to match the input height and adds support for the `className` variable.

fix: Change SelectField CSS to match input height

---

package-lock.json
package.json

This PR upgrades `@dcl/ui-env` to fix an issue where it throws on runtime when it's used on a build that does not have `process` defined (like on Vite or esbuild or other bundlers with their out-of-the-box configuration).
For more info see https://github.com/decentraland/ui-env/pull/10

fix: upgrade @dcl/ui-env

---

src/components/SelectField/SelectField.css
src/components/SelectField/SelectField.stories.tsx

This PR fixes the difference in text heights between the input field and the select field.
Before:
After:

fix: Select and input text height not matching each other

---

src/components/Web2TransactionModal/Web2TransactionModal.css
src/components/Web2TransactionModal/Web2TransactionModal.stories.tsx
src/components/Web2TransactionModal/Web2TransactionModal.tsx
src/components/Web2TransactionModal/index.ts
src/index.ts

This PR adds the Web2 transaction modal, which has the responsibility of showing web2 users the gas cost of their transaction.

feat: Add Web2 transaction modal

---

src/components/WearablePreview/WearablePreview.tsx

This PR adds an optional param `unity` to the WearablePreview component.
This parameter will allow switching to the Unity Renderer when required.

feat: Add unity param to the Wearable Preview
